[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"